const TitleList = [
  {
    id: "newbie",
    title: "Iniciante",
    color: "#8c8c8c",
    effect: "none",
    price: 10,
  },
  {
    id: "adventurer",
    title: "Aventureiro",
    color: "#4682B4",
    effect: "none",
    price: 30,
  },
  {
    id: "explorer",
    title: "Desbravador",
    color: "#32CD32",
    effect: "none",
    price: 50,
  },
  {
    id: "windmaster",
    title: "Mestre dos Ventos",
    color: "#FFD700",
    effect: "none",
    price: 80,
  },
  {
    id: "knight",
    title: "Cavaleiro",
    color: "#C0C0C0",
    effect: "none",
    price: 110,
  },
  {
    id: "realm_guardian",
    title: "Guardião",
    color: "#5900ff",
    effect: "none",
    price: 150,
  },
  {
    id: "treasure_hunter",
    title: "Caçador de Tesouros",
    color: "#d0ff00",
    effect: "none",
    price: 200,
  },
  {
    id: "shadow_of_darkness",
    title: "Senhor das Trevas",
    color: "#000000",
    effect: "none",
    price: 250,
  },
  {
    id: "star_lord",
    title: "Senhor das Estrelas",
    color: "#ADD8E6",
    effect: "particles",
    price: 300,
  },
  {
    id: "legendary",
    title: "Lendário",
    color: "#FF4500",
    effect: "flame",
    price: 350,
  },
  {
    id: "divine",
    title: "Divino",
    color: "#FF1493",
    effect: "radiant_halo",
    price: 400,
  },
  {
    id: "beta",
    title: "Testador do Beta",
    color: "#FF8C00",
    effect: "beta_tester",
    price: 450,
  },
];

export default TitleList;
